### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by skplunkerin** [fega/mongo-server#64]
Pagination in the docs doesn't work, it loads an empty array.
_[doc source](https://nomadas.gitbook.io/mongo-server/basics/routing-and-queries#paginate)_

I created 14 posts, using `GET /posts?$page=2`, or `GET /posts?$page=2&$limit=10`.

**Issue:** empty array returned
**Expected:** 4 posts returned

Versions:
=======
**OS:** `OSX 10.14.5`
**Mongo:** `MongoDB shell version v4.0.3`
**Node:** `12.4.0`
**Moser:** `0.45.0`

**Comment by skplunkerin** [comment]
I'm also noticing there's no "**`Link` header**" to work with.

>"In the `Link` header you'll get `first`, `prev`, `next` and `last` links"

**Comment by fega** [comment]
@skplunkerin keep in mind that the first page is $page=0 (I need to add this to the docs)!

let me know if that solves your issue!

**Comment by skplunkerin** [comment]
@fega that did it, thank you!

**Comment by skplunkerin** [comment]
@fega The `Link` Header is still missing though. Anything I'm missing to get that?

**Comment by fega** [comment]
@skplunkerin this is probably because I based the initial version in json-server, so I initially copied their docs,

that makes me think about that feature, do you think it could be useful? what is your use case

**Comment by skplunkerin** [comment]
@fega haha, makes sense :)

I haven't used `Link` headers before for any API call. But TBH seeing that in the docs (and then researching what it is) got me excited. The idea is pretty smart (especially for API's). This is nice icing on the cake, but not a requirement... but is preferable to what I've seen in other API's (see below old school example):

Going old school, you can leave it as is ("oh, the next page returned 0 results... now I know that the previous page was the last page). This isn't ideal as it makes you do an unnecessary API call to verify what the last page is. The other old school approach is something where the meta info is returned in the response like:

**Old school example:**

```
{
  "total_posts": 500,
  "total_pages": 5,
  "posts": [...] // Array of 100 posts
}
```

As you can see this isn't very clean. I'd rather have the results just showing all posts, and then check the Header for the "meta data".

**Comment by fega** [comment]
I can implement it but as a separate option, because it means an extra query to the DB, 

something like
```
 {
   paginationHeader:true
}
```

**Comment by skplunkerin** [comment]
@fega would I add that then apply to each resource? Or would I need to add that to each resource I want it on?

**Comment by fega** [comment]
Good Question!, probably both ways should be allowed
