### ISSUE TITLE
Swagger Docs isn't really Swagger Docs

### ISSUE THREAD

**Issue by skplunkerin** [fega/mongo-server#66]
See [swagger docs section](https://nomadas.gitbook.io/mongo-server/automatic-documentation/swagger-docs), looks like this is copy-pasted from [this other non-related section (about default values)](https://nomadas.gitbook.io/mongo-server/basics/untitled)

**Comment by fega** [comment]
oh! very strange, probably the link is broken. I'll fix it tonight, thank so much,*

Currently you can use `GET /moser-docs/swagger/` to access to the swagger docs, keep in mind that this still an experimental feature

**Comment by fega** [comment]
actually your use cases gonna be super helpful to improve it :D

**Comment by skplunkerin** [comment]
that fixed it, thanks dude!

**Comment by skplunkerin** [comment]
btw, this is super helpful!
