### ISSUE TITLE
User signup JWT doesn't set $owner field, but User login JWT does

### ISSUE THREAD

**Issue by skplunkerin** [fega/mongo-server#67]
I think the JWT token is getting created differently on **Signup** and **Login** endpoints?

**ISSUE:** When using a fresh JWT from **User signup** (`POST /auth/users/sign-up`), then creating `POST /contacts`... `user_id` is incorrectly set to `null`

**BUT:** When using a JWT from **User login** (`POST /auth/users/log-in`), creating `POST /contacts` correctly sets `user_id` as expected.

---
Here's my resources config for `users` and `contacts` (where `/contacts` will set the `user_id` owner field).

**Config:**

```
  resources: {
    users:{
      auth:{
        local:['email','password', ['posts','cats','contacts']]
      }
    },
    contacts:{
      permissions: [['admin'],['contacts']],
      post:{
        default:(resource,user)=>({
          ...resource,
          $owner:true, // this will be saved as resourceName_id: id, so you can use it with the populate feature defined in the Relationships section
          $timestamps:true, // createdAt, updatedAt
          $version: true,
        })
      }
    },
```

**Comment by fega** [comment]
@skplunkerin Could you give me a little bit more information about what is in the token?
you can use this:
https://jwt.io/

**Comment by skplunkerin** [comment]
@fega I haven't done anything custom for the `$token` response, I'm using the base logic for **User signup** and **login**. Using https://jwt.io/, I get the following different tokens:

**User signup JWT:**

```
{
  "email": "test@example.com",
  "resource": "users",
  "permissions": [
    "posts",
    "cats",
    "contacts"
  ],
  "iat": 1560889617
}
```

**User login JWT:**

```
{
  "resource": "users",
  "_id": "5d094911f1f4df696164a81c",
  "permissions": [
    "posts",
    "cats",
    "contacts"
  ],
  "iat": 1560890086
}
```

_btw, you accidentally closed this issue, unless you fixed it?_

**Comment by fega** [comment]
I accidentally closed it

**Comment by fega** [comment]
@skplunkerin Fixed! thanks so much!

**Comment by skplunkerin** [comment]
@fega I can confirm it works now, thank you!
